coverage:
  status:
    project:
      default:
        # Do not pass if PR reduces coverage by more than 5%
        target: auto
        threshold: 5
comment:
  layout: "header, diff, components, files, footer"
