[package]
name = "axum-opentelemetry-middleware"
version = "0.2.0"
authors = []
edition = "2021"
resolver = "2"
publish = ["famedly"]


[dependencies]
axum = { version = "0.6.1", features = ["headers"] }
bytes = "1.1.0"
futures = "0.3.21"
opentelemetry = { version = "0.18.0", features = ["metrics", "rt-tokio"] }
opentelemetry-prometheus = "0.13.0"
prometheus = "0.13.0"
time = "0.3.9"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
tower = "0.4.12"

[dev-dependencies]
futures = "0.3.21"
http = "0.2.6"
regex = "1.5.5"
